spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youtube??autoReconnect=true&useSSL=false
  session:
    store-type: redis
server:
  port: 8060
  session:
    timeout: 86400

club:
  wenfan:
    youtube:
      code:
        img:
          width: 120
          height: 30
          codeCount: 4
          expiredTime: 60
          url: /url1,/url2/*
      browser:
        rememberSeconds: 120
        loginType: JSON
      jwt:
        secret: mySecret
        expiration: 600000
        head: Authorization
        tokenHead: "Bearer "
        path: auth
        refresh: refresh
        register: auth/register
mybatis:
  mapperLocations: classpath*:club/wenfan/youtube/mapper/xml/*.xml
  type-aliases-package: club.wenfan.youtube.bean
logging:
  level:
    root: info
